# Directories
source: ../.
destination: _site
layouts_dir: docs/_layouts
includes_dir: docs/_includes

# Site title and description
title:              JSON Concepts
description:        JSON Concepts Official Website
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title

# Site base hostname & protocol, e.g. http://example.com
url:                "http://jsonconcepts.github.io"

# Build settings
markdown:           kramdown
highlighter:        rouge

exclude:
  - '**/Gemfile'
  - '**/Gemfile.lock'
  - '**/node_modules'
  - '**/package.json'
  - '**/package-lock.json'
  - '**/*.js'
  - 'LICENSE'

collections:
  theme:
    output: true

# Defaults
defaults:
  - values:
      layout: "default"
      toc: true
