name: DEPLOY WEBSITE
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Merge branch to website
        uses: devmasx/merge-branch@v1.3.1
        with:
          target_branch: website
      
