name: build impl nodejs
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  build-impl-nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Build nodejs implementation
        run: |
          npm install
          cd impl/nodejs
          npm install
          npm test
          npm run coverage
