name: deploy website
on:
  push:
    branches: [ website ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build
      - name: Copy output to docs
        run: mv ./.vuepress/dist ./docs
