name: merge to website
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Merge branch to website
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: website
          github_token: ${{ github.token }}
